# Generated by Django 5.2.5 on 2025-09-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_address_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber/Viewer'), ('editor', 'Editor')], default='subscriber', max_length=20),
        ),
    ]
