# Generated by Django 5.2.5 on 2025-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_profile_pic_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/image/'),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
