# Generated by Django 5.2.5 on 2025-10-08 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_profile_pic_delete_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='default_profile_pic', max_length=255, verbose_name='image'),
        ),
    ]
