# Generated by Django 5.2.5 on 2025-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('editor', 'Editor')], default='subscriber', max_length=20),
        ),
    ]
