# Generated by Django 5.2.5 on 2025-09-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='ratings',
        ),
    ]
