# Generated by Django 5.2.5 on 2025-10-05 16:49

import django.db.models.deletion
import news_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NewsArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', validators=[news_app.validators.validate_file_size])),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_app.newsarticle')),
            ],
        ),
    ]
