# Generated by Django 5.2.5 on 2025-10-08 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_newsarticle_editor_newsarticleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticleimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
