# Generated by Django 5.2.5 on 2025-10-11 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_newsarticleimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsarticle',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_article_title'),
        ),
    ]
