# Generated by Django 5.2.5 on 2025-10-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_newsarticle_unique_article_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='newsarticle',
            name='unique_article_title',
        ),
    ]
